package enums


type AugmentationType int32

const (
    AugmentationTypeNone AugmentationType = AugmentationType(0)
    AugmentationTypeStrength AugmentationType = AugmentationType(1)
    AugmentationTypeEndurance AugmentationType = AugmentationType(2)
    AugmentationTypeCoordination AugmentationType = AugmentationType(3)
    AugmentationTypeQuickness AugmentationType = AugmentationType(4)
    AugmentationTypeFocus AugmentationType = AugmentationType(5)
    AugmentationTypeSelf AugmentationType = AugmentationType(6)
    AugmentationTypeSalvage AugmentationType = AugmentationType(7)
    AugmentationTypeItemTinkering AugmentationType = AugmentationType(8)
    AugmentationTypeArmorTinkering AugmentationType = AugmentationType(9)
    AugmentationTypeMagicItemTinkering AugmentationType = AugmentationType(10)
    AugmentationTypeWeaponTinkering AugmentationType = AugmentationType(11)
    AugmentationTypeBurdenLimit AugmentationType = AugmentationType(13)
    AugmentationTypeDeathItemLoss AugmentationType = AugmentationType(14)
    AugmentationTypeDeathSpellLoss AugmentationType = AugmentationType(15)
    AugmentationTypeCritProtect AugmentationType = AugmentationType(16)
    AugmentationTypeBonusXP AugmentationType = AugmentationType(17)
    AugmentationTypeBonusSalvage AugmentationType = AugmentationType(18)
    AugmentationTypeImbueChance AugmentationType = AugmentationType(19)
    AugmentationTypeRegenBonus AugmentationType = AugmentationType(20)
    AugmentationTypeSpellDuration AugmentationType = AugmentationType(21)
    AugmentationTypeResistSlash AugmentationType = AugmentationType(22)
    AugmentationTypeResistPierce AugmentationType = AugmentationType(23)
    AugmentationTypeResistBludgeon AugmentationType = AugmentationType(24)
    AugmentationTypeResistAcid AugmentationType = AugmentationType(25)
    AugmentationTypeResistFire AugmentationType = AugmentationType(26)
    AugmentationTypeResistCold AugmentationType = AugmentationType(27)
    AugmentationTypeResistElectric AugmentationType = AugmentationType(28)
    AugmentationTypeFociCreature AugmentationType = AugmentationType(29)
    AugmentationTypeFociItem AugmentationType = AugmentationType(30)
    AugmentationTypeFociLife AugmentationType = AugmentationType(31)
    AugmentationTypeFociWar AugmentationType = AugmentationType(32)
    AugmentationTypeCritChance AugmentationType = AugmentationType(33)
    AugmentationTypeCritDamage AugmentationType = AugmentationType(34)
    AugmentationTypeMelee AugmentationType = AugmentationType(35)
    AugmentationTypeMissile AugmentationType = AugmentationType(36)
    AugmentationTypeMagic AugmentationType = AugmentationType(37)
    AugmentationTypeDamage AugmentationType = AugmentationType(38)
    AugmentationTypeDamageResist AugmentationType = AugmentationType(39)
    AugmentationTypeAllStats AugmentationType = AugmentationType(40)
    AugmentationTypeFociVoid AugmentationType = AugmentationType(42)
    )
