package enums


type EmoteCategory int32

const (
    EmoteCategoryInvalid EmoteCategory = EmoteCategory(0)
    EmoteCategoryRefuse EmoteCategory = EmoteCategory(1)
    EmoteCategoryVendor EmoteCategory = EmoteCategory(2)
    EmoteCategoryDeath EmoteCategory = EmoteCategory(3)
    EmoteCategoryPortal EmoteCategory = EmoteCategory(4)
    EmoteCategoryHeartBeat EmoteCategory = EmoteCategory(5)
    EmoteCategoryGive EmoteCategory = EmoteCategory(6)
    EmoteCategoryUse EmoteCategory = EmoteCategory(7)
    EmoteCategoryActivation EmoteCategory = EmoteCategory(8)
    EmoteCategoryGeneration EmoteCategory = EmoteCategory(9)
    EmoteCategoryPickUp EmoteCategory = EmoteCategory(10)
    EmoteCategoryDrop EmoteCategory = EmoteCategory(11)
    EmoteCategoryQuestSuccess EmoteCategory = EmoteCategory(12)
    EmoteCategoryQuestFailure EmoteCategory = EmoteCategory(13)
    EmoteCategoryTaunt EmoteCategory = EmoteCategory(14)
    EmoteCategoryWoundedTaunt EmoteCategory = EmoteCategory(15)
    EmoteCategoryKillTaunt EmoteCategory = EmoteCategory(16)
    EmoteCategoryNewEnemy EmoteCategory = EmoteCategory(17)
    EmoteCategoryScream EmoteCategory = EmoteCategory(18)
    EmoteCategoryHomesick EmoteCategory = EmoteCategory(19)
    EmoteCategoryReceiveCritical EmoteCategory = EmoteCategory(20)
    EmoteCategoryResistSpell EmoteCategory = EmoteCategory(21)
    EmoteCategoryTestSuccess EmoteCategory = EmoteCategory(22)
    EmoteCategoryTestFailure EmoteCategory = EmoteCategory(23)
    EmoteCategoryHearChat EmoteCategory = EmoteCategory(24)
    EmoteCategoryWield EmoteCategory = EmoteCategory(25)
    EmoteCategoryUnWield EmoteCategory = EmoteCategory(26)
    EmoteCategoryEventSuccess EmoteCategory = EmoteCategory(27)
    EmoteCategoryEventFailure EmoteCategory = EmoteCategory(28)
    EmoteCategoryTestNoQuality EmoteCategory = EmoteCategory(29)
    EmoteCategoryQuestNoFellow EmoteCategory = EmoteCategory(30)
    EmoteCategoryTestNoFellow EmoteCategory = EmoteCategory(31)
    EmoteCategoryGotoSet EmoteCategory = EmoteCategory(32)
    EmoteCategoryNumFellowsSuccess EmoteCategory = EmoteCategory(33)
    EmoteCategoryNumFellowsFailure EmoteCategory = EmoteCategory(34)
    EmoteCategoryNumCharacterTitlesSuccess EmoteCategory = EmoteCategory(35)
    EmoteCategoryNumCharacterTitlesFailure EmoteCategory = EmoteCategory(36)
    EmoteCategoryReceiveLocalSignal EmoteCategory = EmoteCategory(37)
    )
