package enums

type EquipMask uint32

const (
	EquipMaskNone               EquipMask = EquipMask(0x00000000)
	EquipMaskHeadWear           EquipMask = EquipMask(0x00000001)
	EquipMaskChestWear          EquipMask = EquipMask(0x00000002)
	EquipMaskAbdomenWear        EquipMask = EquipMask(0x00000004)
	EquipMaskUpperArmWear       EquipMask = EquipMask(0x00000008)
	EquipMaskLowerArmWear       EquipMask = EquipMask(0x00000010)
	EquipMaskHandWear           EquipMask = EquipMask(0x00000020)
	EquipMaskUpperLegWear       EquipMask = EquipMask(0x00000040)
	EquipMaskLowerLegWear       EquipMask = EquipMask(0x00000080)
	EquipMaskFootWear           EquipMask = EquipMask(0x00000100)
	EquipMaskChestArmor         EquipMask = EquipMask(0x00000200)
	EquipMaskAbdomenArmor       EquipMask = EquipMask(0x00000400)
	EquipMaskUpperArmArmor      EquipMask = EquipMask(0x00000800)
	EquipMaskLowerArmArmor      EquipMask = EquipMask(0x00001000)
	EquipMaskUpperLegArmor      EquipMask = EquipMask(0x00002000)
	EquipMaskLowerLegArmor      EquipMask = EquipMask(0x00004000)
	EquipMaskNeckWear           EquipMask = EquipMask(0x00008000)
	EquipMaskWristWearLeft      EquipMask = EquipMask(0x00010000)
	EquipMaskWristWearRight     EquipMask = EquipMask(0x00020000)
	EquipMaskFingerWearLeft     EquipMask = EquipMask(0x00040000)
	EquipMaskFingerWearRight    EquipMask = EquipMask(0x00080000)
	EquipMaskMeleeWeapon        EquipMask = EquipMask(0x00100000)
	EquipMaskShield             EquipMask = EquipMask(0x00200000)
	EquipMaskMissileWeapon      EquipMask = EquipMask(0x00400000)
	EquipMaskMissileAmmo        EquipMask = EquipMask(0x00800000)
	EquipMaskHeld               EquipMask = EquipMask(0x01000000)
	EquipMaskTwoHanded          EquipMask = EquipMask(0x02000000)
	EquipMaskTrinketOne         EquipMask = EquipMask(0x04000000)
	EquipMaskCloak              EquipMask = EquipMask(0x08000000)
	EquipMaskSigilOne           EquipMask = EquipMask(0x10000000)
	EquipMaskSigilTwo           EquipMask = EquipMask(0x20000000)
	EquipMaskSigilThree         EquipMask = EquipMask(0x40000000)
	EquipMaskClothing           EquipMask = EquipMask(0x80000000 | EquipMaskHeadWear | EquipMaskChestWear | EquipMaskAbdomenWear | EquipMaskUpperArmWear | EquipMaskLowerArmWear | EquipMaskHandWear | EquipMaskUpperLegWear | EquipMaskLowerLegWear | EquipMaskFootWear)
	EquipMaskArmor              EquipMask = EquipMask(EquipMaskChestArmor | EquipMaskAbdomenArmor | EquipMaskUpperArmArmor | EquipMaskLowerArmArmor | EquipMaskUpperLegArmor | EquipMaskLowerLegArmor | EquipMaskFootWear)
	EquipMaskArmorExclusive     EquipMask = EquipMask(EquipMaskChestArmor | EquipMaskAbdomenArmor | EquipMaskUpperArmArmor | EquipMaskLowerArmArmor | EquipMaskUpperLegArmor | EquipMaskLowerLegArmor)
	EquipMaskExtremity          EquipMask = EquipMask(EquipMaskHeadWear | EquipMaskHandWear | EquipMaskFootWear)
	EquipMaskJewelry            EquipMask = EquipMask(EquipMaskNeckWear | EquipMaskWristWearLeft | EquipMaskWristWearRight | EquipMaskFingerWearLeft | EquipMaskFingerWearRight | EquipMaskTrinketOne | EquipMaskCloak | EquipMaskSigilOne | EquipMaskSigilTwo | EquipMaskSigilThree)
	EquipMaskWristWear          EquipMask = EquipMask(EquipMaskWristWearLeft | EquipMaskWristWearRight)
	EquipMaskFingerWear         EquipMask = EquipMask(EquipMaskFingerWearLeft | EquipMaskFingerWearRight)
	EquipMaskSigil              EquipMask = EquipMask(EquipMaskSigilOne | EquipMaskSigilTwo | EquipMaskSigilThree)
	EquipMaskReadySlot          EquipMask = EquipMask(EquipMaskHeld | EquipMaskTwoHanded | EquipMaskTrinketOne | EquipMaskCloak | EquipMaskSigilOne | EquipMaskSigilTwo)
	EquipMaskWeapon             EquipMask = EquipMask(EquipMaskSigilTwo | EquipMaskTrinketOne | EquipMaskHeld)
	EquipMaskWeaponReadySlot    EquipMask = EquipMask(EquipMaskSigilOne | EquipMaskSigilTwo | EquipMaskTrinketOne | EquipMaskHeld)
	EquipMaskSelectable         EquipMask = EquipMask(EquipMaskMeleeWeapon | EquipMaskShield | EquipMaskMissileWeapon | EquipMaskHeld | EquipMaskTwoHanded)
	EquipMaskSelectablePlusAmmo EquipMask = EquipMask(EquipMaskSelectable | EquipMaskMissileAmmo)
	EquipMaskAll                EquipMask = EquipMask(0x7FFFFFFF)
)
