package enums

type ItemType uint32

const (
	ItemTypeNone                              ItemType = ItemType(0x00000000)
	ItemTypeMeleeWeapon                       ItemType = ItemType(0x00000001)
	ItemTypeArmor                             ItemType = ItemType(0x00000002)
	ItemTypeClothing                          ItemType = ItemType(0x00000004)
	ItemTypeJewelry                           ItemType = ItemType(0x00000008)
	ItemTypeCreature                          ItemType = ItemType(0x00000010)
	ItemTypeFood                              ItemType = ItemType(0x00000020)
	ItemTypeMoney                             ItemType = ItemType(0x00000040)
	ItemTypeMisc                              ItemType = ItemType(0x00000080)
	ItemTypeMissileWeapon                     ItemType = ItemType(0x00000100)
	ItemTypeContainer                         ItemType = ItemType(0x00000200)
	ItemTypeUseless                           ItemType = ItemType(0x00000400)
	ItemTypeGem                               ItemType = ItemType(0x00000800)
	ItemTypeSpellComponents                   ItemType = ItemType(0x00001000)
	ItemTypeWritable                          ItemType = ItemType(0x00002000)
	ItemTypeKey                               ItemType = ItemType(0x00004000)
	ItemTypeCaster                            ItemType = ItemType(0x00008000)
	ItemTypePortal                            ItemType = ItemType(0x00010000)
	ItemTypeLockable                          ItemType = ItemType(0x00020000)
	ItemTypePromissoryNote                    ItemType = ItemType(0x00040000)
	ItemTypeManaStone                         ItemType = ItemType(0x00080000)
	ItemTypeService                           ItemType = ItemType(0x00100000)
	ItemTypeMagicWieldable                    ItemType = ItemType(0x00200000)
	ItemTypeCraftCookingBase                  ItemType = ItemType(0x00400000)
	ItemTypeCraftAlchemyBase                  ItemType = ItemType(0x00800000)
	ItemTypeCraftFletchingBase                ItemType = ItemType(0x02000000)
	ItemTypeCraftAlchemyIntermediate          ItemType = ItemType(0x04000000)
	ItemTypeCraftFletchingIntermediate        ItemType = ItemType(0x08000000)
	ItemTypeLifeStone                         ItemType = ItemType(0x10000000)
	ItemTypeTinkeringTool                     ItemType = ItemType(0x20000000)
	ItemTypeTinkeringMaterial                 ItemType = ItemType(0x40000000)
	ItemTypeGameboard                         ItemType = ItemType(0x80000000)
	ItemTypePortalMagicTarget                 ItemType = ItemType(ItemTypePortal | ItemTypeLifeStone)
	ItemTypeLockableMagicTarget               ItemType = ItemType(ItemTypeMisc | ItemTypeContainer)
	ItemTypeVestements                        ItemType = ItemType(ItemTypeArmor | ItemTypeClothing)
	ItemTypeWeapon                            ItemType = ItemType(ItemTypeMeleeWeapon | ItemTypeMissileWeapon)
	ItemTypeWeaponOrCaster                    ItemType = ItemType(ItemTypeMeleeWeapon | ItemTypeMissileWeapon | ItemTypeCaster)
	ItemTypeItem                              ItemType = ItemType(ItemTypeMeleeWeapon | ItemTypeArmor | ItemTypeClothing | ItemTypeJewelry | ItemTypeFood | ItemTypeMoney | ItemTypeMisc | ItemTypeMissileWeapon | ItemTypeContainer | ItemTypeGem | ItemTypeSpellComponents | ItemTypeWritable | ItemTypeKey | ItemTypeCaster | ItemTypePortal | ItemTypePromissoryNote | ItemTypeManaStone | ItemTypeMagicWieldable)
	ItemTypeRedirectableItemEnchantmentTarget ItemType = ItemType(ItemTypeMeleeWeapon | ItemTypeArmor | ItemTypeClothing | ItemTypeMissileWeapon | ItemTypeCaster)
	ItemTypeItemEnchantableTarget             ItemType = ItemType(ItemTypeMeleeWeapon | ItemTypeArmor | ItemTypeClothing | ItemTypeJewelry | ItemTypeMisc | ItemTypeMissileWeapon | ItemTypeContainer | ItemTypeGem | ItemTypeCaster | ItemTypeManaStone)
	ItemTypeVendorShopKeep                    ItemType = ItemType(ItemTypeMeleeWeapon | ItemTypeArmor | ItemTypeClothing | ItemTypeFood | ItemTypeMisc | ItemTypeMissileWeapon | ItemTypeContainer | ItemTypeUseless | ItemTypeWritable | ItemTypeKey | ItemTypePromissoryNote | ItemTypeCraftFletchingIntermediate | ItemTypeTinkeringMaterial)
	ItemTypeVendorGrocer                      ItemType = ItemType(ItemTypeFood | ItemTypeContainer | ItemTypeWritable | ItemTypeKey | ItemTypePromissoryNote | ItemTypeCraftCookingBase)
)
