package enums


type Placement uint32

const (
    PlacementDefault Placement = Placement(0)
    PlacementRightHandCombat Placement = Placement(1)
    PlacementRightHandNonCombat Placement = Placement(2)
    PlacementLeftHand Placement = Placement(3)
    PlacementBelt Placement = Placement(4)
    PlacementQuiver Placement = Placement(5)
    PlacementShield Placement = Placement(6)
    PlacementLeftWeapon Placement = Placement(7)
    PlacementLeftUnarmed Placement = Placement(8)
    PlacementSpecialCrowssbowBolt Placement = Placement(51)
    PlacementMissileFlight Placement = Placement(52)
    PlacementResting Placement = Placement(101)
    PlacementOther Placement = Placement(102)
    PlacementHook Placement = Placement(103)
    PlacementRandom1 Placement = Placement(121)
    PlacementRandom2 Placement = Placement(122)
    PlacementRandom3 Placement = Placement(123)
    PlacementRandom4 Placement = Placement(124)
    PlacementRandom5 Placement = Placement(125)
    PlacementRandom6 Placement = Placement(126)
    PlacementRandom7 Placement = Placement(127)
    PlacementRandom8 Placement = Placement(128)
    PlacementRandom9 Placement = Placement(129)
    PlacementRandom10 Placement = Placement(130)
    PlacementXXXUnknownA Placement = Placement(0x0000000A)
    PlacementXXXUnknownF Placement = Placement(0x0000000F)
    PlacementXXXUnknown14 Placement = Placement(0x00000014)
    PlacementXXXUnknown1E Placement = Placement(0x0000001E)
    PlacementXXXUnknown20 Placement = Placement(0x00000020)
    PlacementXXXUnknown3C Placement = Placement(0x0000003C)
    PlacementXXXUnknown69 Placement = Placement(0x00000069)
    PlacementXXXUnknown6A Placement = Placement(0x0000006A)
    PlacementXXXUnknown63 Placement = Placement(0x00000063)
    PlacementXXXUnknown68 Placement = Placement(0x00000068)
    PlacementXXXUnknown78 Placement = Placement(0x00000078)
    PlacementXXXUnknown84 Placement = Placement(0x00000084)
    PlacementXXXUnknownF0 Placement = Placement(0x000000F0)
    PlacementXXXUnknown3F2 Placement = Placement(0x000003F2)
    )
