package enums

type Skill int32

const (
	SkillNone                Skill = Skill(0)
	SkillMeleeDefense        Skill = Skill(1)
	SkillMissileDefense      Skill = Skill(2)
	SkillArcaneLore          Skill = Skill(3)
	SkillMagicDefense        Skill = Skill(4)
	SkillManaConversion      Skill = Skill(5)
	SkillItemTinkering       Skill = Skill(6)
	SkillAssessPerson        Skill = Skill(7)
	SkillDeception           Skill = Skill(8)
	SkillHealing             Skill = Skill(9)
	SkillJump                Skill = Skill(10)
	SkillLockpick            Skill = Skill(11)
	SkillRun                 Skill = Skill(12)
	SkillAssessCreature      Skill = Skill(13)
	SkillWeaponTinkering     Skill = Skill(14)
	SkillArmorTinkering      Skill = Skill(15)
	SkillMagicItemTinkering  Skill = Skill(16)
	SkillCreatureEnchantment Skill = Skill(17)
	SkillItemEnchantment     Skill = Skill(18)
	SkillLifeMagic           Skill = Skill(19)
	SkillWarMagic            Skill = Skill(20)
	SkillLeadership          Skill = Skill(21)
	SkillLoyalty             Skill = Skill(22)
	SkillFletching           Skill = Skill(23)
	SkillAlchemy             Skill = Skill(24)
	SkillCooking             Skill = Skill(25)
	SkillSalvaging           Skill = Skill(26)
	SkillTwoHandedCombat     Skill = Skill(27)
	SkillVoidMagic           Skill = Skill(28)
	SkillHeavyWeapons        Skill = Skill(29)
	SkillLightWeapons        Skill = Skill(30)
	SkillFinesseWeapons      Skill = Skill(31)
	SkillMissileWeapons      Skill = Skill(32)
	SkillShield              Skill = Skill(33)
	SkillDualWield           Skill = Skill(34)
	SkillRecklessness        Skill = Skill(35)
	SkillSneakAttack         Skill = Skill(36)
	SkillDirtyFighting       Skill = Skill(37)
)
