package enums


type SurfacePixelFormat uint32

const (
    SurfacePixelFormatPFID_UNKNOWN SurfacePixelFormat = SurfacePixelFormat(0)
    SurfacePixelFormatPFID_R8G8B8 SurfacePixelFormat = SurfacePixelFormat(20)
    SurfacePixelFormatPFID_A8R8G8B8 SurfacePixelFormat = SurfacePixelFormat(21)
    SurfacePixelFormatPFID_X8R8G8B8 SurfacePixelFormat = SurfacePixelFormat(22)
    SurfacePixelFormatPFID_R5G6B5 SurfacePixelFormat = SurfacePixelFormat(23)
    SurfacePixelFormatPFID_X1R5G5B5 SurfacePixelFormat = SurfacePixelFormat(24)
    SurfacePixelFormatPFID_A1R5G5B5 SurfacePixelFormat = SurfacePixelFormat(25)
    SurfacePixelFormatPFID_A4R4G4B4 SurfacePixelFormat = SurfacePixelFormat(26)
    SurfacePixelFormatPFID_R3G3B2 SurfacePixelFormat = SurfacePixelFormat(27)
    SurfacePixelFormatPFID_A8 SurfacePixelFormat = SurfacePixelFormat(28)
    SurfacePixelFormatPFID_A8R3G3B2 SurfacePixelFormat = SurfacePixelFormat(29)
    SurfacePixelFormatPFID_X4R4G4B4 SurfacePixelFormat = SurfacePixelFormat(30)
    SurfacePixelFormatPFID_A2B10G10R10 SurfacePixelFormat = SurfacePixelFormat(31)
    SurfacePixelFormatPFID_A8B8G8R8 SurfacePixelFormat = SurfacePixelFormat(32)
    SurfacePixelFormatPFID_X8B8G8R8 SurfacePixelFormat = SurfacePixelFormat(33)
    SurfacePixelFormatPFID_A2R10G10B10 SurfacePixelFormat = SurfacePixelFormat(35)
    SurfacePixelFormatPFID_A8P8 SurfacePixelFormat = SurfacePixelFormat(40)
    SurfacePixelFormatPFID_P8 SurfacePixelFormat = SurfacePixelFormat(41)
    SurfacePixelFormatPFID_L8 SurfacePixelFormat = SurfacePixelFormat(50)
    SurfacePixelFormatPFID_A8L8 SurfacePixelFormat = SurfacePixelFormat(51)
    SurfacePixelFormatPFID_A4L4 SurfacePixelFormat = SurfacePixelFormat(52)
    SurfacePixelFormatPFID_V8U8 SurfacePixelFormat = SurfacePixelFormat(60)
    SurfacePixelFormatPFID_L6V5U5 SurfacePixelFormat = SurfacePixelFormat(61)
    SurfacePixelFormatPFID_X8L8V8U8 SurfacePixelFormat = SurfacePixelFormat(62)
    SurfacePixelFormatPFID_Q8W8V8U8 SurfacePixelFormat = SurfacePixelFormat(63)
    SurfacePixelFormatPFID_V16U16 SurfacePixelFormat = SurfacePixelFormat(64)
    SurfacePixelFormatPFID_A2W10V10U10 SurfacePixelFormat = SurfacePixelFormat(67)
    SurfacePixelFormatPFID_D16_LOCKABLE SurfacePixelFormat = SurfacePixelFormat(70)
    SurfacePixelFormatPFID_D32 SurfacePixelFormat = SurfacePixelFormat(71)
    SurfacePixelFormatPFID_D15S1 SurfacePixelFormat = SurfacePixelFormat(73)
    SurfacePixelFormatPFID_D24S8 SurfacePixelFormat = SurfacePixelFormat(75)
    SurfacePixelFormatPFID_D24X8 SurfacePixelFormat = SurfacePixelFormat(77)
    SurfacePixelFormatPFID_D24X4S4 SurfacePixelFormat = SurfacePixelFormat(79)
    SurfacePixelFormatPFID_D16 SurfacePixelFormat = SurfacePixelFormat(80)
    SurfacePixelFormatPFID_VERTEXDATA SurfacePixelFormat = SurfacePixelFormat(100)
    SurfacePixelFormatPFID_INDEX16 SurfacePixelFormat = SurfacePixelFormat(101)
    SurfacePixelFormatPFID_INDEX32 SurfacePixelFormat = SurfacePixelFormat(102)
    SurfacePixelFormatPFID_CUSTOM_R8G8B8A8 SurfacePixelFormat = SurfacePixelFormat(240)
    SurfacePixelFormatPFID_CUSTOM_FIRST SurfacePixelFormat = SurfacePixelFormat(240)
    SurfacePixelFormatPFID_CUSTOM_A8B8G8R8 SurfacePixelFormat = SurfacePixelFormat(241)
    SurfacePixelFormatPFID_CUSTOM_B8G8R8 SurfacePixelFormat = SurfacePixelFormat(242)
    SurfacePixelFormatPFID_CUSTOM_LSCAPE_R8G8B8 SurfacePixelFormat = SurfacePixelFormat(243)
    SurfacePixelFormatPFID_CUSTOM_LSCAPE_ALPHA SurfacePixelFormat = SurfacePixelFormat(244)
    SurfacePixelFormatPFID_CUSTOM_LAST SurfacePixelFormat = SurfacePixelFormat(500)
    SurfacePixelFormatPFID_CUSTOM_RAW_JPEG SurfacePixelFormat = SurfacePixelFormat(500)
    SurfacePixelFormatPFID_DXT1 SurfacePixelFormat = SurfacePixelFormat(827611204)
    SurfacePixelFormatPFID_DXT2 SurfacePixelFormat = SurfacePixelFormat(844388420)
    SurfacePixelFormatPFID_YUY2 SurfacePixelFormat = SurfacePixelFormat(844715353)
    SurfacePixelFormatPFID_DXT3 SurfacePixelFormat = SurfacePixelFormat(861165636)
    SurfacePixelFormatPFID_DXT4 SurfacePixelFormat = SurfacePixelFormat(877942852)
    SurfacePixelFormatPFID_DXT5 SurfacePixelFormat = SurfacePixelFormat(894720068)
    SurfacePixelFormatPFID_G8R8_G8B8 SurfacePixelFormat = SurfacePixelFormat(1111970375)
    SurfacePixelFormatPFID_R8G8_B8G8 SurfacePixelFormat = SurfacePixelFormat(1195525970)
    SurfacePixelFormatPFID_UYVY SurfacePixelFormat = SurfacePixelFormat(1498831189)
    SurfacePixelFormatPFID_INVALID SurfacePixelFormat = SurfacePixelFormat(2147483647)
    )
