package enums


type TreasureClass int32

const (
    TreasureClassUndef TreasureClass = TreasureClass(0)
    TreasureClassPyreal TreasureClass = TreasureClass(1)
    TreasureClassGem TreasureClass = TreasureClass(2)
    TreasureClassJewelry TreasureClass = TreasureClass(3)
    TreasureClassArtObject TreasureClass = TreasureClass(4)
    TreasureClassWeapon TreasureClass = TreasureClass(5)
    TreasureClassArmor TreasureClass = TreasureClass(6)
    TreasureClassClothing TreasureClass = TreasureClass(7)
    TreasureClassScroll TreasureClass = TreasureClass(8)
    TreasureClassCaster TreasureClass = TreasureClass(9)
    TreasureClassManaStone TreasureClass = TreasureClass(10)
    TreasureClassConsumable TreasureClass = TreasureClass(11)
    TreasureClassHealKit TreasureClass = TreasureClass(12)
    TreasureClassLockpick TreasureClass = TreasureClass(13)
    TreasureClassSpellComponent TreasureClass = TreasureClass(14)
    TreasureClassStuddedLeatherArmor TreasureClass = TreasureClass(15)
    TreasureClassChainMailArmor TreasureClass = TreasureClass(16)
    TreasureClassCovenantArmor TreasureClass = TreasureClass(17)
    TreasureClassPlateMailArmor TreasureClass = TreasureClass(18)
    TreasureClassHeritageLowArmor TreasureClass = TreasureClass(19)
    TreasureClassHeritageHighArmor TreasureClass = TreasureClass(20)
    TreasureClassSwordWeapon TreasureClass = TreasureClass(21)
    TreasureClassMaceWeapon TreasureClass = TreasureClass(22)
    TreasureClassAxeWeapon TreasureClass = TreasureClass(23)
    TreasureClassSpearWeapon TreasureClass = TreasureClass(24)
    TreasureClassUnarmedWeapon TreasureClass = TreasureClass(25)
    TreasureClassStaffWeapon TreasureClass = TreasureClass(26)
    TreasureClassDaggerWeapon TreasureClass = TreasureClass(27)
    TreasureClassBowWeapon TreasureClass = TreasureClass(28)
    TreasureClassCrossbowWeapon TreasureClass = TreasureClass(29)
    TreasureClassSocietyArmor TreasureClass = TreasureClass(30)
    TreasureClassSocietyBreastplate TreasureClass = TreasureClass(31)
    TreasureClassSocietyGauntlets TreasureClass = TreasureClass(32)
    TreasureClassSocietyGirth TreasureClass = TreasureClass(33)
    TreasureClassSocietyGreaves TreasureClass = TreasureClass(34)
    TreasureClassSocietyHelm TreasureClass = TreasureClass(35)
    TreasureClassSocietyPauldrons TreasureClass = TreasureClass(36)
    TreasureClassSocietyTassets TreasureClass = TreasureClass(37)
    TreasureClassSocietyVambraces TreasureClass = TreasureClass(38)
    TreasureClassSocietySollerets TreasureClass = TreasureClass(39)
    TreasureClassCloak TreasureClass = TreasureClass(40)
    TreasureClassPetDevice TreasureClass = TreasureClass(41)
    TreasureClassEncapsulatedSpirit TreasureClass = TreasureClass(42)
    )
