package enums


type WeenieType uint32

const (
    WeenieTypeUndef WeenieType = WeenieType(0)
    WeenieTypeGeneric WeenieType = WeenieType(1)
    WeenieTypeClothing WeenieType = WeenieType(2)
    WeenieTypeMissileLauncher WeenieType = WeenieType(3)
    WeenieTypeMissile WeenieType = WeenieType(4)
    WeenieTypeAmmunition WeenieType = WeenieType(5)
    WeenieTypeMeleeWeapon WeenieType = WeenieType(6)
    WeenieTypePortal WeenieType = WeenieType(7)
    WeenieTypeBook WeenieType = WeenieType(8)
    WeenieTypeCoin WeenieType = WeenieType(9)
    WeenieTypeCreature WeenieType = WeenieType(10)
    WeenieTypeAdmin WeenieType = WeenieType(11)
    WeenieTypeVendor WeenieType = WeenieType(12)
    WeenieTypeHotSpot WeenieType = WeenieType(13)
    WeenieTypeCorpse WeenieType = WeenieType(14)
    WeenieTypeCow WeenieType = WeenieType(15)
    WeenieTypeAI WeenieType = WeenieType(16)
    WeenieTypeMachine WeenieType = WeenieType(17)
    WeenieTypeFood WeenieType = WeenieType(18)
    WeenieTypeDoor WeenieType = WeenieType(19)
    WeenieTypeChest WeenieType = WeenieType(20)
    WeenieTypeContainer WeenieType = WeenieType(21)
    WeenieTypeKey WeenieType = WeenieType(22)
    WeenieTypeLockpick WeenieType = WeenieType(23)
    WeenieTypePressurePlate WeenieType = WeenieType(24)
    WeenieTypeLifeStone WeenieType = WeenieType(25)
    WeenieTypeSwitch WeenieType = WeenieType(26)
    WeenieTypePKModifier WeenieType = WeenieType(27)
    WeenieTypeHealer WeenieType = WeenieType(28)
    WeenieTypeLightSource WeenieType = WeenieType(29)
    WeenieTypeAllegiance WeenieType = WeenieType(30)
    WeenieTypeSpellComponent WeenieType = WeenieType(31)
    WeenieTypeProjectileSpell WeenieType = WeenieType(32)
    WeenieTypeScroll WeenieType = WeenieType(33)
    WeenieTypeCaster WeenieType = WeenieType(34)
    WeenieTypeChannel WeenieType = WeenieType(35)
    WeenieTypeManaStone WeenieType = WeenieType(36)
    WeenieTypeGem WeenieType = WeenieType(37)
    WeenieTypeAdvocateFane WeenieType = WeenieType(38)
    WeenieTypeAdvocateItem WeenieType = WeenieType(39)
    WeenieTypeSentinel WeenieType = WeenieType(40)
    WeenieTypeGSpellEconomy WeenieType = WeenieType(41)
    WeenieTypeLSpellEconomy WeenieType = WeenieType(42)
    WeenieTypeCraftTool WeenieType = WeenieType(43)
    WeenieTypeLScoreKeeper WeenieType = WeenieType(44)
    WeenieTypeGScoreKeeper WeenieType = WeenieType(45)
    WeenieTypeGScoreGatherer WeenieType = WeenieType(46)
    WeenieTypeScoreBook WeenieType = WeenieType(47)
    WeenieTypeEventCoordinator WeenieType = WeenieType(48)
    WeenieTypeEntity WeenieType = WeenieType(49)
    WeenieTypeStackable WeenieType = WeenieType(50)
    WeenieTypeHUD WeenieType = WeenieType(51)
    WeenieTypeHouse WeenieType = WeenieType(52)
    WeenieTypeDeed WeenieType = WeenieType(53)
    WeenieTypeSlumLord WeenieType = WeenieType(54)
    WeenieTypeHook WeenieType = WeenieType(55)
    WeenieTypeStorage WeenieType = WeenieType(56)
    WeenieTypeBootSpot WeenieType = WeenieType(57)
    WeenieTypeHousePortal WeenieType = WeenieType(58)
    WeenieTypeGame WeenieType = WeenieType(59)
    WeenieTypeGamePiece WeenieType = WeenieType(60)
    WeenieTypeSkillAlterationDevice WeenieType = WeenieType(61)
    WeenieTypeAttributeTransferDevice WeenieType = WeenieType(62)
    WeenieTypeHooker WeenieType = WeenieType(63)
    WeenieTypeAllegianceBindstone WeenieType = WeenieType(64)
    WeenieTypeInGameStatKeeper WeenieType = WeenieType(65)
    WeenieTypeAugmentationDevice WeenieType = WeenieType(66)
    WeenieTypeSocialManager WeenieType = WeenieType(67)
    WeenieTypePet WeenieType = WeenieType(68)
    WeenieTypePetDevice WeenieType = WeenieType(69)
    )
