package enums


type WeenieErrorWithString int32

const (
    WeenieErrorWithString_IsTooBusyToAcceptGifts WeenieErrorWithString = WeenieErrorWithString(0x001E)
    WeenieErrorWithString_CannotCarryAnymore WeenieErrorWithString = WeenieErrorWithString(0x002B)
    WeenieErrorWithStringYouFailToAffect_YouCannotAffectAnyone WeenieErrorWithString = WeenieErrorWithString(0x004E)
    WeenieErrorWithStringYouFailToAffect_TheyCannotBeHarmed WeenieErrorWithString = WeenieErrorWithString(0x004F)
    WeenieErrorWithStringYouFailToAffect_WithBeneficialSpells WeenieErrorWithString = WeenieErrorWithString(0x0050)
    WeenieErrorWithStringYouFailToAffect_YouAreNotPK WeenieErrorWithString = WeenieErrorWithString(0x0051)
    WeenieErrorWithStringYouFailToAffect_TheyAreNotPK WeenieErrorWithString = WeenieErrorWithString(0x0052)
    WeenieErrorWithStringYouFailToAffect_NotSamePKType WeenieErrorWithString = WeenieErrorWithString(0x0053)
    WeenieErrorWithStringYouFailToAffect_AcrossHouseBoundary WeenieErrorWithString = WeenieErrorWithString(0x0054)
    WeenieErrorWithString_IsNotAcceptingGiftsRightNow WeenieErrorWithString = WeenieErrorWithString(0x03EF)
    WeenieErrorWithString_IsAlreadyOneOfYourFollowers WeenieErrorWithString = WeenieErrorWithString(0x0413)
    WeenieErrorWithString_CannotHaveAnyMoreVassals WeenieErrorWithString = WeenieErrorWithString(0x0416)
    WeenieErrorWithString_DoesntKnowWhatToDoWithThat WeenieErrorWithString = WeenieErrorWithString(0x046A)
    WeenieErrorWithStringYouMustBeAboveLevel_ToBuyHouse WeenieErrorWithString = WeenieErrorWithString(0x0488)
    WeenieErrorWithStringYouMustBeAtOrBelowLevel_ToBuyHouse WeenieErrorWithString = WeenieErrorWithString(0x0489)
    WeenieErrorWithStringYouMustBeAboveAllegianceRank_ToBuyHouse WeenieErrorWithString = WeenieErrorWithString(0x048B)
    WeenieErrorWithStringYouMustBeAtOrBelowAllegianceRank_ToBuyHouse WeenieErrorWithString = WeenieErrorWithString(0x048C)
    WeenieErrorWithStringThe_WasNotSuitableForSalvaging WeenieErrorWithString = WeenieErrorWithString(0x04BF)
    WeenieErrorWithStringThe_ContainseTheWrongMaterial WeenieErrorWithString = WeenieErrorWithString(0x04C0)
    WeenieErrorWithStringYouMustBe_ToUseItemMagic WeenieErrorWithString = WeenieErrorWithString(0x04C6)
    WeenieErrorWithStringYour_IsTooLowToUseItemMagic WeenieErrorWithString = WeenieErrorWithString(0x04C9)
    WeenieErrorWithStringOnly_MayUseItemMagic WeenieErrorWithString = WeenieErrorWithString(0x04CA)
    WeenieErrorWithStringYouMustSpecialize_ToUseItemMagic WeenieErrorWithString = WeenieErrorWithString(0x04CB)
    WeenieErrorWithStringAiRefuseItemDuringEmote WeenieErrorWithString = WeenieErrorWithString(0x04CE)
    WeenieErrorWithString_CannotAcceptStackedItems WeenieErrorWithString = WeenieErrorWithString(0x04CF)
    WeenieErrorWithStringYour_SkillMustBeTrained WeenieErrorWithString = WeenieErrorWithString(0x04D1)
    WeenieErrorWithStringNotEnoughSkillCreditsToSpecialize WeenieErrorWithString = WeenieErrorWithString(0x04D2)
    WeenieErrorWithStringTooMuchXPToRecoverFromSkill WeenieErrorWithString = WeenieErrorWithString(0x04D3)
    WeenieErrorWithStringYour_SkillIsAlreadyUntrained WeenieErrorWithString = WeenieErrorWithString(0x04D4)
    WeenieErrorWithStringCannotLowerSkillWhileWieldingItem WeenieErrorWithString = WeenieErrorWithString(0x04D5)
    WeenieErrorWithStringYouHaveSucceededSpecializing_Skill WeenieErrorWithString = WeenieErrorWithString(0x04D6)
    WeenieErrorWithStringYouHaveSucceededUnspecializing_Skill WeenieErrorWithString = WeenieErrorWithString(0x04D7)
    WeenieErrorWithStringYouHaveSucceededUntraining_Skill WeenieErrorWithString = WeenieErrorWithString(0x04D8)
    WeenieErrorWithStringCannotUntrain_SkillButRecoveredXP WeenieErrorWithString = WeenieErrorWithString(0x04D9)
    WeenieErrorWithStringTooManyCreditsInSpecializedSkills WeenieErrorWithString = WeenieErrorWithString(0x04DA)
    )
