package properties

type PropertyInstanceId uint16

const (
	PropertyInstanceIdUndef                            PropertyInstanceId = PropertyInstanceId(0)
	PropertyInstanceIdOwner                            PropertyInstanceId = PropertyInstanceId(1)
	PropertyInstanceIdContainer                        PropertyInstanceId = PropertyInstanceId(2)
	PropertyInstanceIdWielder                          PropertyInstanceId = PropertyInstanceId(3)
	PropertyInstanceIdFreezer                          PropertyInstanceId = PropertyInstanceId(4)
	PropertyInstanceIdViewer                           PropertyInstanceId = PropertyInstanceId(5)
	PropertyInstanceIdGenerator                        PropertyInstanceId = PropertyInstanceId(6)
	PropertyInstanceIdScribe                           PropertyInstanceId = PropertyInstanceId(7)
	PropertyInstanceIdCurrentCombatTarget              PropertyInstanceId = PropertyInstanceId(8)
	PropertyInstanceIdCurrentEnemy                     PropertyInstanceId = PropertyInstanceId(9)
	PropertyInstanceIdProjectileLauncher               PropertyInstanceId = PropertyInstanceId(10)
	PropertyInstanceIdCurrentAttacker                  PropertyInstanceId = PropertyInstanceId(11)
	PropertyInstanceIdCurrentDamager                   PropertyInstanceId = PropertyInstanceId(12)
	PropertyInstanceIdCurrentFollowTarget              PropertyInstanceId = PropertyInstanceId(13)
	PropertyInstanceIdCurrentAppraisalTarget           PropertyInstanceId = PropertyInstanceId(14)
	PropertyInstanceIdCurrentFellowshipAppraisalTarget PropertyInstanceId = PropertyInstanceId(15)
	PropertyInstanceIdActivationTarget                 PropertyInstanceId = PropertyInstanceId(16)
	PropertyInstanceIdCreator                          PropertyInstanceId = PropertyInstanceId(17)
	PropertyInstanceIdVictim                           PropertyInstanceId = PropertyInstanceId(18)
	PropertyInstanceIdKiller                           PropertyInstanceId = PropertyInstanceId(19)
	PropertyInstanceIdVendor                           PropertyInstanceId = PropertyInstanceId(20)
	PropertyInstanceIdCustomer                         PropertyInstanceId = PropertyInstanceId(21)
	PropertyInstanceIdBonded                           PropertyInstanceId = PropertyInstanceId(22)
	PropertyInstanceIdWounder                          PropertyInstanceId = PropertyInstanceId(23)
	PropertyInstanceIdAllegiance                       PropertyInstanceId = PropertyInstanceId(24)
	PropertyInstanceIdPatron                           PropertyInstanceId = PropertyInstanceId(25)
	PropertyInstanceIdMonarch                          PropertyInstanceId = PropertyInstanceId(26)
	PropertyInstanceIdCombatTarget                     PropertyInstanceId = PropertyInstanceId(27)
	PropertyInstanceIdHealthQueryTarget                PropertyInstanceId = PropertyInstanceId(28)
	PropertyInstanceIdLastUnlocker                     PropertyInstanceId = PropertyInstanceId(29)
	PropertyInstanceIdCrashAndTurnTarget               PropertyInstanceId = PropertyInstanceId(30)
	PropertyInstanceIdAllowedActivator                 PropertyInstanceId = PropertyInstanceId(31)
	PropertyInstanceIdHouseOwner                       PropertyInstanceId = PropertyInstanceId(32)
	PropertyInstanceIdHouse                            PropertyInstanceId = PropertyInstanceId(33)
	PropertyInstanceIdSlumlord                         PropertyInstanceId = PropertyInstanceId(34)
	PropertyInstanceIdManaQueryTarget                  PropertyInstanceId = PropertyInstanceId(35)
	PropertyInstanceIdCurrentGame                      PropertyInstanceId = PropertyInstanceId(36)
	PropertyInstanceIdRequestedAppraisalTarget         PropertyInstanceId = PropertyInstanceId(37)
	PropertyInstanceIdAllowedWielder                   PropertyInstanceId = PropertyInstanceId(38)
	PropertyInstanceIdAssignedTarget                   PropertyInstanceId = PropertyInstanceId(39)
	PropertyInstanceIdLimboSource                      PropertyInstanceId = PropertyInstanceId(40)
	PropertyInstanceIdSnooper                          PropertyInstanceId = PropertyInstanceId(41)
	PropertyInstanceIdTeleportedCharacter              PropertyInstanceId = PropertyInstanceId(42)
	PropertyInstanceIdPet                              PropertyInstanceId = PropertyInstanceId(43)
	PropertyInstanceIdPetOwner                         PropertyInstanceId = PropertyInstanceId(44)
	PropertyInstanceIdPetDevice                        PropertyInstanceId = PropertyInstanceId(45)
	PropertyInstanceIdPCAPRecordedObjectIID            PropertyInstanceId = PropertyInstanceId(8000)
)
